<a href="https://colab.research.google.com/github/abubakarchigarialiyu-wq/print-Welcome-to-Chigari-InsightAI-/blob/main/Chigari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:

!pip -q install pandas plotly openpyxl

print("Chigari InsightAI")
print("Required libraries installed successfully!")

Chigari InsightAI
Required libraries installed successfully!

In [6]:
import pandas as pd
import plotly.express as px

from IPython.display import display
from google.colab import files

print("Libraries imported successfully!")

Libraries imported successfully!

In [7]:
data = {
    "State": [
        "Kano", "Lagos", "Kaduna",
        "Kano", "Lagos", "Kaduna"
    ],

    "Year": [
        2019, 2019, 2019,
        2023, 2023, 2023
    ],

    "Registered_Voters": [
        5000000, 6500000, 4000000,
        5800000, 7000000, 4500000
    ],

    "Votes_Cast": [
        2100000, 2200000, 1500000,
        1800000, 1900000, 1300000
    ]
}

df = pd.DataFrame(data)

print("Sample dataset created successfully!")

display(df)

Sample dataset created successfully!

    State  Year  Registered_Voters  Votes_Cast
0    Kano  2019            5000000     2100000
1   Lagos  2019            6500000     2200000
2  Kaduna  2019            4000000     1500000
3    Kano  2023            5800000     1800000
4   Lagos  2023            7000000     1900000
5  Kaduna  2023            4500000     1300000

In [8]:
df["Turnout_Percent"] = (
    df["Votes_Cast"] /
    df["Registered_Voters"] * 100
).round(2)

print("Turnout calculated successfully!")

display(df)

Turnout calculated successfully!

    State  Year  Registered_Voters  Votes_Cast  Turnout_Percent
0    Kano  2019            5000000     2100000            42.00
1   Lagos  2019            6500000     2200000            33.85
2  Kaduna  2019            4000000     1500000            37.50
3    Kano  2023            5800000     1800000            31.03
4   Lagos  2023            7000000     1900000            27.14
5  Kaduna  2023            4500000     1300000            28.89

In [9]:
print("DATASET OVERVIEW")

print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

print("\nColumn names:")
print(list(df.columns))

print("\nFirst five records:")
display(df.head())

DATASET OVERVIEW
Total rows: 6
Total columns: 5

Column names:
['State', 'Year', 'Registered_Voters', 'Votes_Cast', 'Turnout_Percent']

First five records:

    State  Year  Registered_Voters  Votes_Cast  Turnout_Percent
0    Kano  2019            5000000     2100000            42.00
1   Lagos  2019            6500000     2200000            33.85
2  Kaduna  2019            4000000     1500000            37.50
3    Kano  2023            5800000     1800000            31.03
4   Lagos  2023            7000000     1900000            27.14

In [10]:
print("DATA QUALITY CHECK")

print("\nMissing values:")
display(df.isnull().sum())

print("\nDuplicate records:")
print(df.duplicated().sum())

DATA QUALITY CHECK

Missing values:

State                0
Year                 0
Registered_Voters    0
Votes_Cast           0
Turnout_Percent      0
dtype: int64

Duplicate records:
0

In [11]:
print("STATISTICAL SUMMARY")

display(df.describe().round(2))

STATISTICAL SUMMARY

          Year  Registered_Voters  Votes_Cast  Turnout_Percent
count     6.00               6.00        6.00             6.00
mean   2021.00         5466666.67  1800000.00            33.40
std       2.19         1169045.19   346410.16             5.59
min    2019.00         4000000.00  1300000.00            27.14
25%    2019.00         4625000.00  1575000.00            29.42
50%    2021.00         5400000.00  1850000.00            32.44
75%    2023.00         6325000.00  2050000.00            36.59
max    2023.00         7000000.00  2200000.00            42.00

In [12]:
fig = px.bar(
    df,
    x="State",
    y="Turnout_Percent",
    color="Year",
    barmode="group",
    title="Sample Election Turnout by State and Year",
    labels={
        "State": "State",
        "Turnout_Percent": "Turnout (%)",
        "Year": "Election Year"
    }
)

fig.show()

In [13]:
state_summary = (
    df.groupby("State")["Turnout_Percent"]
    .mean()
    .round(2)
    .reset_index()
)


def ask_your_data(question):
    question = question.lower()

    if "highest" in question and "turnout" in question:
        result = state_summary.loc[
            state_summary["Turnout_Percent"].idxmax()
        ]

        return (
            f'{result["State"]} has the highest average '
            f'turnout at {result["Turnout_Percent"]}%.'
        )

    elif "lowest" in question and "turnout" in question:
        result = state_summary.loc[
            state_summary["Turnout_Percent"].idxmin()
        ]

        return (
            f'{result["State"]} has the lowest average '
            f'turnout at {result["Turnout_Percent"]}%.'
        )

    elif "average" in question and "turnout" in question:
        average = round(df["Turnout_Percent"].mean(), 2)

        return f"The average sample turnout is {average}%."

    elif "how many" in question or "number of records" in question:
        return f"The dataset contains {len(df)} records."

    elif "columns" in question:
        return f"Dataset columns: {', '.join(df.columns)}."

    else:
        return (
            "I cannot answer that question yet. Try asking about "
            "the highest turnout, lowest turnout, average turnout, "
            "number of records, or columns."
        )


print(ask_your_data("Which state has the highest turnout?"))
print(ask_your_data("What is the average turnout?"))
print(ask_your_data("How many records are in the dataset?"))

Kano has the highest average turnout at 36.52%.
The average sample turnout is 33.4%.
The dataset contains 6 records.

In [14]:
average_turnout = round(df["Turnout_Percent"].mean(), 2)

highest_row = df.loc[df["Turnout_Percent"].idxmax()]
lowest_row = df.loc[df["Turnout_Percent"].idxmin()]

report = f"""
CHIGARI INSIGHTAI
Turn Data Into Clear Insights

DATASET SUMMARY
---------------
Total records: {len(df)}
States included: {df["State"].nunique()}
Years included: {sorted(df["Year"].unique())}

KEY FINDINGS
------------
Average sample turnout: {average_turnout}%.

Highest sample turnout:
{highest_row["State"]}, {highest_row["Year"]}:
{highest_row["Turnout_Percent"]}%.

Lowest sample turnout:
{lowest_row["State"]}, {lowest_row["Year"]}:
{lowest_row["Turnout_Percent"]}%.

NOTE
----
This report uses fictional sample data for testing.
It does not represent official election statistics.
"""

print(report)

CHIGARI INSIGHTAI
Turn Data Into Clear Insights

DATASET SUMMARY
---------------
Total records: 6
States included: 3
Years included: [np.int64(2019), np.int64(2023)]

KEY FINDINGS
------------
Average sample turnout: 33.4%.

Highest sample turnout:
Kano, 2019:
42.0%.

Lowest sample turnout:
Lagos, 2023:
27.14%.

NOTE
----
This report uses fictional sample data for testing.
It does not represent official election statistics.

In [15]:
uploaded = files.upload()

if uploaded:
    filename = next(iter(uploaded))

    if filename.lower().endswith(".csv"):
        user_df = pd.read_csv(filename)

    elif filename.lower().endswith((".xlsx", ".xls")):
        user_df = pd.read_excel(filename)

    else:
        raise ValueError(
            "Please upload a CSV or Excel file."
        )

    print("File uploaded successfully!")
    print("Rows:", user_df.shape[0])
    print("Columns:", user_df.shape[1])

    display(user_df.head(10))

else:
    print("No file was uploaded.")

No file was uploaded.

In [16]:

if "user_df" in globals():
    analysis_df = user_df.copy()
else:
    analysis_df = df.copy()

print("CHIGARI INSIGHTAI - SMART ANALYZER")

print("\nDataset size:")
print("Rows:", len(analysis_df))
print("Columns:", len(analysis_df.columns))

print("\nColumn information:")

column_info = pd.DataFrame({
    "Column": analysis_df.columns,
    "Data Type": analysis_df.dtypes.astype(str).values,
    "Missing Values": analysis_df.isnull().sum().values,
    "Unique Values": analysis_df.nunique().values
})

display(column_info)

numeric_columns = analysis_df.select_dtypes(
    include="number"
).columns.tolist()

print("\nNumerical columns:", numeric_columns)

for column in numeric_columns:
    average = analysis_df[column].mean()

    if pd.notna(average):
        print(f"Average {column}: {average:,.2f}")

if numeric_columns:
    selected_column = numeric_columns[0]

    chart_df = analysis_df.dropna(
        subset=[selected_column]
    )

    if not chart_df.empty:
        fig = px.histogram(
            chart_df,
            x=selected_column,
            title=f"Distribution of {selected_column}"
        )

        fig.show()
else:
    print("No numerical columns available for charting.")

CHIGARI INSIGHTAI - SMART ANALYZER

Dataset size:
Rows: 6
Columns: 5

Column information:

              Column Data Type  Missing Values  Unique Values
0              State    object               0              3
1               Year     int64               0              2
2  Registered_Voters     int64               0              6
3         Votes_Cast     int64               0              6
4    Turnout_Percent   float64               0              6

Numerical columns: ['Year', 'Registered_Voters', 'Votes_Cast', 'Turnout_Percent']
Average Year: 2,021.00
Average Registered_Voters: 5,466,666.67
Average Votes_Cast: 1,800,000.00
Average Turnout_Percent: 33.40

In [17]:
# ==========================================
# CHIGARI INSIGHTAI
# SMART DATA ANALYZER - UPGRADE 1
# ==========================================

import pandas as pd
import plotly.express as px
from IPython.display import display, Markdown

# Select the dataset
if "user_df" in globals() and isinstance(user_df, pd.DataFrame):
    analysis_df = user_df.copy()
else:
    analysis_df = df.copy()

print("CHIGARI INSIGHTAI")
print("Turn Data Into Clear Insights")
print("=" * 45)

# Dataset overview
print("\n1. DATASET OVERVIEW")
print("Total records:", len(analysis_df))
print("Total columns:", len(analysis_df.columns))

print("\n2. COLUMN NAMES")
print(list(analysis_df.columns))

# Data quality checks
print("\n3. DATA QUALITY")
print("Missing values:", int(analysis_df.isnull().sum().sum()))
print("Duplicate rows:", int(analysis_df.duplicated().sum()))

# Numerical summary
print("\n4. NUMERICAL SUMMARY")

numeric_df = analysis_df.select_dtypes(include="number")

if not numeric_df.empty:
    display(numeric_df.describe().round(2))
else:
    print("No numerical columns found.")

# Automatically choose a useful chart
print("\n5. AUTOMATIC VISUALIZATION")

if "Turnout_Percent" in analysis_df.columns:
    fig = px.bar(
        analysis_df,
        x="State" if "State" in analysis_df.columns else analysis_df.index,
        y="Turnout_Percent",
        color="Year" if "Year" in analysis_df.columns else None,
        title="Election Turnout Analysis",
        labels={"Turnout_Percent": "Turnout (%)"}
    )

elif len(numeric_df.columns) > 0:
    chart_column = numeric_df.columns[0]

    fig = px.histogram(
        analysis_df,
        x=chart_column,
        title=f"Distribution of {chart_column}"
    )

else:
    fig = None
    print("No suitable numerical column is available for a chart.")

if fig is not None:
    fig.show()

# Generate automatic insights
print("\n6. AUTOMATIC INSIGHTS")

if "Turnout_Percent" in analysis_df.columns and not analysis_df.empty:

    valid_turnout = analysis_df.dropna(subset=["Turnout_Percent"])

    if not valid_turnout.empty:
        highest = valid_turnout.loc[
            valid_turnout["Turnout_Percent"].idxmax()
        ]

        lowest = valid_turnout.loc[
            valid_turnout["Turnout_Percent"].idxmin()
        ]

        average = valid_turnout["Turnout_Percent"].mean()

        print(
            f"Highest turnout: {highest['Turnout_Percent']:.2f}%"
        )

        if "State" in valid_turnout.columns:
            print("State with highest turnout:", highest["State"])

        print(
            f"Lowest turnout: {lowest['Turnout_Percent']:.2f}%"
        )

        if "State" in valid_turnout.columns:
            print("State with lowest turnout:", lowest["State"])

        print(f"Average turnout: {average:.2f}%")

print("\nAnalysis completed successfully!")
print("Note: Sample figures are fictional and are for demonstration only.")

CHIGARI INSIGHTAI
Turn Data Into Clear Insights
=============================================

1. DATASET OVERVIEW
Total records: 6
Total columns: 5

2. COLUMN NAMES
['State', 'Year', 'Registered_Voters', 'Votes_Cast', 'Turnout_Percent']

3. DATA QUALITY
Missing values: 0
Duplicate rows: 0

4. NUMERICAL SUMMARY

          Year  Registered_Voters  Votes_Cast  Turnout_Percent
count     6.00               6.00        6.00             6.00
mean   2021.00         5466666.67  1800000.00            33.40
std       2.19         1169045.19   346410.16             5.59
min    2019.00         4000000.00  1300000.00            27.14
25%    2019.00         4625000.00  1575000.00            29.42
50%    2021.00         5400000.00  1850000.00            32.44
75%    2023.00         6325000.00  2050000.00            36.59
max    2023.00         7000000.00  2200000.00            42.00

5. AUTOMATIC VISUALIZATION

6. AUTOMATIC INSIGHTS
Highest turnout: 42.00%
State with highest turnout: Kano
Lowest turnout: 27.14%
State with lowest turnout: Lagos
Average turnout: 33.40%

Analysis completed successfully!
Note: Sample figures are fictional and are for demonstration only.